name: Build iOS App

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build iOS (no codesign)
      run: flutter build ios --release --no-codesign
    
    - name: Create IPA
      run: |
        mkdir Payload
        cp -r build/ios/iphoneos/Runner.app Payload
        zip -r the_glitch_app.ipa Payload
    
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: ios-app
        path: the_glitch_app.ipa

